name: voicenotes
description: "Speak and Save: An Audio Note-Taking Solution Using Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Audio recording and playback
  flutter_sound: ^9.2.13
  audioplayers: ^6.0.0

  # Permissions
  permission_handler: ^11.3.1

  # Storage and file management
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  path: ^1.8.3

  # State management and utilities
  provider: ^6.1.1
  intl: ^0.19.0

  # UI Components
  flutter_staggered_animations: ^1.1.1

  # Routing
  go_router: ^14.2.0

  # Supabase (auth, db, storage)
  supabase_flutter: ^2.6.0

  # Transcription (on-device speech recognition) → upgraded to resolve conflict
  speech_to_text: ^7.3.0

  # Full-text search (bundled SQLite with FTS)
  sqlite3_flutter_libs: ^0.5.24

  # Export & sharing
  pdf: ^3.11.1
  printing: ^5.13.4
  share_plus: ^10.0.2
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  open_filex: ^4.5.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # Security
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3

  # HTTP/LLM for summaries (optional)
  http: ^1.2.2
  dart_openai: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
